version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: vaccinecounter # change the password
      POSTGRES_USER: vaccinecounter
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432  
  server:   
    depends_on:
      - database
    links:
      - database
    image: ghcr.io/mathisburger/vaccinecounter
    ports:
      - 80:80
    env:
      APP_ENV: prod
      APP_SECRET: 04830082c147c44ca3753649ccc06ebf # use other secret
      APP_VERSION: v1.0.0
      DATABASE_URL: "postgresql://vaccinecounter:vaccinecounter@database:5432/app?serverVersion=13&charset=utf8" # change the password

volumes:
  db-data:
