version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
