index:
    path: /{reactRouting}
    controller: App\Controller\ReactController::navigate
    methods: GET
    defaults:
        reactRouting: null
    requirements:
        reactRouting: '^(?!api).+'

