index:
    path: /{reactRouting}
    controller: App\Controller\ReactController::navigate
    methods: GET
    defaults:
        reactRouting: null
    requirements:
        reactRouting: '^(?!api).+'      

information:
    path: /api/getInformation
    controller: App\Controller\InformationController::getAsJSON
    methods: GET

getNumberOfCounts:
    path: /api/counts/getNumberOfCounts
    controller: App\Controller\CountController::getNumberOfCounts
    methods: GET

createCount:
    path: /api/counts/createCount
    controller: App\Controller\CountController::createCount
    methods: POST

removeCount:
    path: /api/counts/removeCount
    controller: App\Controller\CountController::removeOldestActiveCount
    methods: POST        